name: hpv vaccine notice
on: [push]
# on:
#   schedule:
#     - cron: '0 3 * * *'
jobs:
  hpv-vaccine-notice:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Run script '
        run: echo "RESULT_SHELL=$(bash ./miaomiao.sh)" > $GITHUB_ENV
      # 使用现成的发送邮箱的GitHub action来发送邮件
      - name: 'get result'
        run: echo $env.RESULT_SHELL
      - name: 'Send mail'
        if: ${{ env.RESULT_SHELL != 'nothing' }}
        uses: dawidd6/action-send-mail@master
        with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
          server_address: smtp.qq.com
          server_port: 465
          # 这些sectret的环境变量需要配置在setting中的secret下
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: hpv vaccine notice
          body: ${{ env.RESULT_SHELL }}
          to: 1358995237@qq.com
          from: GitHub Actions
          content_type: text/html
